version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    links:
      - database
    volumes:
      - .:/home/app
  database:
    image: mongo
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root"
      - MONGO_INITDB_ROOT_PASSWORD=root"
      - MONGO_INITDB_DATABASE=rest"
    volumes:
      - db-data:/data/db
      # mysql -> /var/lib/mysql
      # postgres -> /var/lib/postgresql/data
volumes:
  db-data:
